Spectra: Update to v0.0.10
conda-forge/spectra-feedstock pull request #1
Opened 2018-01-13 17:28 UTC by ewels

2018-01-13 17:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2018-01-16 01:05 UTC, epruesse commented
I've restarted the AppVeyor build -- the failures were claiming the bat file was missing, so potentially just a build system issue. Travis seems to be just way backlogged on the macos builds.

2018-01-16 01:12 UTC, ewels commented
Thanks @epruesse! Any idea why my earlier commits with the versions specified failed? It shouldn’t matter I think, just curious what I did wrong..

2018-01-16 01:15 UTC, epruesse commented
@ewels Whitespace. It needs to be `- package versionspec` so `networkx =2.0`. There also can't be a whitespace between the comparison operator and the value, so no `- networkx >= 2`.

2018-01-16 01:26 UTC, epruesse commented
@ewels The failures on AppVeyor for py2.7 and py3.6 didn't go away. Maybe ask on gitter? Or try a manual rerender of the feedstock?

2018-01-16 09:53 UTC, ewels commented
Yeah, I had the same problem with https://github.com/conda-forge/colormath-feedstock/pull/2 and I just merged anyway. The docs all seem to say that there's no need for a `bat` file but then it fails for that reason, which makes no sense for me.

Phil

2018-01-16 19:02 UTC, epruesse commented
Try to rerender the feedstock. Maybe the scripts need to be updated. Looking at the history for conda-forge/staged-recipes, the problem doesn't appear to exist there. If that fails, ping core...

2018-01-17 13:54 UTC, mbargull requested changes
Dependencies need to be version-constrained, matching `setuptools`' `install_requires` (otherwise you'll need to patch `requirements.txt` or `setup.py` to modify those).
Also, this package could be build with `noarch: python`, i.e.,
```yaml
build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
```
. That way you needn't care about AppVeyor.
But either way you'll need to rerender the feedstock.

2018-01-17 13:54 UTC, mbargull commented on recipe/meta.yaml
>      - colormath
This needs
```yaml
  - networkx ==2.0
  - colormath ==3.0.0
```
due to
https://github.com/jsvine/spectra/blob/v0.0.10/requirements.txt
https://github.com/jsvine/spectra/blob/v0.0.10/setup.py#L2
https://github.com/jsvine/spectra/blob/v0.0.10/setup.py#L9-L10
https://github.com/jsvine/spectra/blob/v0.0.10/setup.py#L40

2018-01-17 16:56 UTC, ewels commented
@conda-forge-admin, please rerender

2018-01-17 17:02 UTC, mbargull commented
Yeah, just like a pro, @ewels! Good job!

2018-01-17 17:04 UTC, ewels commented
Haha, thanks for the tuition @mbargull 😉

2018-01-17 17:04 UTC, merged